Change `password` configs type to `Password`.
logstash-plugins/logstash-output-email pull request #65
Opened 2022-12-05 12:43 UTC by mashhurs

### Description
This PR ensures to protect the `password` from leaks in the debug logs.

- Closes #64 

### Test
```
# config
input {
  stdin {}
}
output {
    email {
      to => 'technical@example.com'
      from => 'monitor@example.com'
      subject => 'Alert - %{title}'
      body => "Tags:"
      template_file => "/tmp/email_template.mustache"
      domain => 'mail.example.com'
      port => 25
    }
}
```

```
# Log before change
    [2022-12-01T18:12:18,435][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@password = "super-secret"
    [2022-12-01T18:12:18,435][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@port = 25
    [2022-12-01T18:12:18,435][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@subject = "Alert - %{title}"
    [2022-12-01T18:12:18,435][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@domain = "mail.example.com"
    [2022-12-01T18:12:18,435][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@from = "monitor@example.com"
    [2022-12-01T18:12:18,435][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@to = "technical@example.com"

# Log after change
    [2022-12-01T18:20:07,714][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@password = <password>
    [2022-12-01T18:20:07,714][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@port = 25
    [2022-12-01T18:20:07,714][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@subject = "Alert - %{title}"
    [2022-12-01T18:20:07,714][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@domain = "mail.example.com"
    [2022-12-01T18:20:07,714][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@from = "monitor@example.com"
    [2022-12-01T18:20:07,714][DEBUG][logstash.outputs.email   ] config LogStash::Outputs::Email/@to = "technical@example.com"
```

2023-05-25 15:10 UTC, roaksoax requested changes
Please add (at least) one tests that makes sure that when setting this config option, the value is of password type.

2023-05-27 21:06 UTC, mashhurs commented
> Please add (at least) one tests that makes sure that when setting this config option, the value is of password type.



> Please add (at least) one tests that makes sure that when setting this config option, the value is of password type.

Added a [test case with recent commit](https://github.com/logstash-plugins/logstash-output-email/pull/65/commits/f1c9466d0c243f1cc70bbf81a2616534e42a9c15) at least to guarantee not to leak in debug logs (I think this will be decent since config debug also consequently converts the sensitive data to string).
But in order to run Logstash + this plugin with `--config.debug` and check, we will need a separate docker CI runs can catches the debug logs (even I don't know how to do it for now tbh).

2023-05-30 13:09 UTC, roaksoax commented
lgtm!

2023-05-30 13:10 UTC, roaksoax approved these changes

2023-05-30 14:10 UTC, merged