Upgrade email dependency to fix the Ruby net-smtp load regression.
logstash-plugins/logstash-output-email pull request #69
Opened 2023-09-28 23:27 UTC by mashhurs

### Description
`output-email` plugin with  Logstash 8.10+ versions raises a `LoadError: no such file to load -- net/smtp` error.
It is due to ruby 3.1 regression that marks `net-smtp` as a bundled gem: https://github.com/ruby/ruby/pull/4530

### Solution
`output-email` plugin uses `mail` gem and bundled `net-smtp` gem with ruby 3.1 support was added: https://github.com/mikel/mail/commit/d9d8dcc6bae1774a033ad488cea6217db3a3ebf3
So, we need to update `mail` dependency to `2.8.+` versions.

- Closes #68

2023-09-29 14:13 UTC, mashhurs commented
🔴 CI is a transient.

2023-10-03 09:40 UTC, jsvd requested changes
With mail 2.8, mime-types is no longer a dependency (replaced by `mini-mime`), so we can remove it.

2023-10-03 09:40 UTC, jsvd commented on logstash-output-email.gemspec
>    # mime-types >= 3 require ruby 2.0 support
```suggestion
```

2023-10-03 09:40 UTC, jsvd commented on logstash-output-email.gemspec
> +  s.add_runtime_dependency 'mime-types', '>= 3' # < 3 uses numbered parameter which is deprecated
```suggestion
```

2023-10-03 14:59 UTC, mashhurs commented
🔴 CI is a transient.

2023-10-03 15:14 UTC, jsvd approved these changes
LGTM

2023-10-03 15:25 UTC, merged